#!/bin/sh

WORKDIR=`pwd`
CFGFILE="$WORKDIR/config.yml"

if [ ! -f "$CFGFILE" ]; then
    echo "No config.yml found — starting in Setup Mode (WebUI only)..."
    cat > "$CFGFILE" << 'YAML'
# SMTP2Graph — Generated by Setup Wizard
# Complete the setup via the WebUI at http://<host>:3000

mode: full

webui:
  enabled: true
  port: 3000
  listenAddress: 0.0.0.0
  username: admin
  password: changeme
YAML
fi

# Ensure schema file is available in working directory
ln -sf /usr/local/bin/smtp2graph/config.schema.json /data/config.schema.json

# Run SMTP2Graph
exec node /usr/local/bin/smtp2graph/server.js --receive.port=587
